version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DATABSE= open_cook_dev
      - POSTGRES_DB= open_cook_dev
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD=
    volumes:
      - ./data:/var/lib/postgresql/data
      
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    volumes:
      - './data:/var/lib/redis/data'

  mysql:
    image: mariadb
    restart: always
    command: --explicit_defaults_for_timestamp
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data:/var/lib/mysql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - postgres
