app:
  default_locale: ru
  time_zone: Moscow
  secret_key_base: '000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
  secret_token: '000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'

  mailer:
    service: test
    host: localhost

    smtp:
      default:
        address: smtp.yandex.ru
        domain: yandex.ru
        port: 25
        user_name: test@test.com
        password:
        authentication: plain

      rails_shop:
        address: smtp.yandex.ru
        domain: yandex.ru
        port: 25
        user_name: test@test.com
        password:
        authentication: plain

oauth:
  vkontakte:
    app_id: '000000000'
    app_secret: '000000000'

  facebook:
    app_id: '000000000'
    app_secret: '000000000'

  twitter:
    app_id: '000000000'
    app_secret: '000000000'

  google_oauth2:
    app_id: '000000000'
    app_secret: '000000000'

  odnoklassniki:
    app_id: '000000000'
    app_secret: '000000000'
    app_public: '000000000'

action_cable:
  adapter_params:
    adapter: redis
    url: redis://localhost:6010

  worker_pool_size: 4

  mount_path: ws://localhost:3000/app-cable
  disable_request_forgery_protection: false
  allowed_request_origins: http://localhost:3000

redis:
  port: 6010
  url: redis://localhost:6010

sidekiq:
  namespace: open-cook.ru-dev

rails_shop:
  currancy: RU
  shop_id: '000000000'
  scid: '000000000'
  shop_password: '000000000'
  payment_url: https://money.yandex.ru/eshop.xml
