#
# dev: docker compose -f docker-compose.yml up
# PLATFORM=arm APP_PORT=3000:3000 RUN_AS=7777:7777 docker compose -f docker-compose.yml up
# PLATFORM=amd APP_PORT=3000:3000 RUN_AS=7777:7777 docker compose -f docker-compose.yml up -d
#
# docker exec -ti open_cook-rails-1 bash
version: '3.8'

name: open_cook

services:
  # port: 5432
  psql:
    image: postgres:15.1-bullseye
    user: ${RUN_AS:-root}
    # restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../db/PGSQL:/var/lib/postgresql/data/pgdata
      - ../shared:/shared

  # port: 6379
  # command: redis-server --save 60 1 --loglevel warning
  redis:
    image: redis:7.0.5-alpine
    user: ${RUN_AS:-root}
    volumes:
      - ../db/REDIS:/data
      - ../shared:/shared

  # sidekiq_web:
  #   image: iamteacher/sidekiq:web.arm64
  #   environment:
  #     REDIS_URL: redis://redis:6379
  #     SIDEKIQ_USER: admin
  #     SIDEKIQ_PASSWORD: qwerty
  #   ports:
  #     - 3030:3030
  #   depends_on:
  #     - redis

  # port: 36307
  #
  # docker exec -ti open_cook-sphinx-1 ash
  #
  # docker exec open_cook-sphinx-1 indexer --all --config /opt/sphinx/conf/sphinx.conf
  # docker exec open_cook-sphinx-1 indexer --all --config /opt/sphinx/conf/sphinx.conf --rotate
  #
  sphinx:
    image: macbre/sphinxsearch:3.4.1
    user: ${RUN_AS:-root}
    environment:
      - SPHINX_CONFIG_FILE=/opt/sphinx/conf/sphinx.conf
    volumes:
      - ../config/SPHINX:/opt/sphinx/conf
      - ../db/SPHINX:/opt/sphinx/index
      - ../shared:/shared
    mem_limit: 512m

  # port 3000
  #
  # docker exec -ti open_cook-rails-1 bash
  #
  # RAILS_ENV=development bundle exec rake ts:configure
  # docker exec open_cook-sphinx-1 indexer --all --config /opt/sphinx/conf/sphinx.conf --rotate
  #
  # bundle exec rails s -p 3000 -b 0.0.0.0
  # bundle exec puma -C config/PUMA.production.rb
  #
  rails:
    tty: true
    stdin_open: true
    image: iamteacher/opencook.ru:2022.${PLATFORM:-arm}64
    volumes:
      - ../:/home/lucky/app
      - ../shared:/shared
      - ../db/SPNINX:/opt/sphinx/index
    ports:
      - ${APP_PORT:-3000:3000}
    depends_on:
      - psql
