#
# docker-compose -f docker-compose.yml up
# docker-compose -f docker-compose.yml down
#
# docker exec -ti docker-rails-1 /bin/bash
# docker exec -ti docker-psql-1 /bin/bash
version: '3.8'

name: open_cook

services:
  # port: 5432
  psql:
    image: postgres:15.1-bullseye
    # restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../db/PGSQL:/var/lib/postgresql/data/pgdata
      - ../shared:/shared

  # port: 6379
  # command: redis-server --save 60 1 --loglevel warning
  redis:
    image: redis:7.0.5-alpine
    volumes:
      - ../db/REDIS:/data
      - ../shared:/shared

  # sidekiq_web:
  #   image: iamteacher/sidekiq:web.arm64
  #   environment:
  #     REDIS_URL: redis://redis:6379
  #     SIDEKIQ_USER: admin
  #     SIDEKIQ_PASSWORD: qwerty
  #   ports:
  #     - 3030:3030
  #   depends_on:
  #     - redis

  # docker exec -ti docker-sphinx-1 ash
  # docker-compose run docker-sphinx-1 indexer --all --config /opt/sphinx/conf/sphinx.conf
  # port: 36307
  sphinx:
    image: macbre/sphinxsearch:3.4.1
    environment:
      - SPHINX_CONFIG_FILE=/opt/sphinx/conf/sphinx.conf
    volumes:
      - ../db/SPHINX:/opt/sphinx/index
      - ../config/SPHINX:/opt/sphinx/conf
      - ../shared:/shared
    mem_limit: 512m

  # rails s -p 3000 -b 0.0.0.0
  # port 3000
  rails:
    tty: true
    stdin_open: true
    image: iamteacher/opencook.ru:webapp.arm64
    volumes:
      - ../:/home
    depends_on:
      - psql
      - sphinx
      - redis
