---
:verbose: true
:concurrency: 10
:logfile: /home/log/sidekiq.log
:pidfile: /home/tmp/pids/sidekiq.pid

:queues:
  - [critical, 5]
  - [default,  2]
  - [mailers,  2]
  - [low,      1]

# gem 'sidekiq-limit_fetch'
#
# :limits:
#   critical: 5
#   default:  2
#   mailers:  1
#   low:      1
