development:
  mysql41: 5432
  address: sphinx

  min_infix_len: 3
  morphology: 'stem_en, stem_ru'

  indices_location:   /opt/sphinx/index
  configuration_file: <%= Rails.root.to_s %>/config/SPHINX/sphinx.conf

  log:         /shared/searchd.development.log
  query_log:   /shared/searchd.development.query.log

  binlog_path: /shared
  pid_file:    /shared/searchd.development.pid
